### ISSUE TITLE
Properties Symbol.toPrimitive and Symbol.iterator does not exist

### ISSUE THREAD

**Issue by justinmchase** [cmd-johnson/deno-reflect-metadata#6]
```sh
> import { Reflect } from "https://deno.land/x/reflect_metadata@v0.1.12/mod.ts";
Download https://deno.land/x/reflect_metadata@v0.1.12/mod.ts
Download https://deno.land/x/reflect_metadata@v0.1.12/Reflect.ts
Check https://deno.land/x/reflect_metadata@v0.1.12/mod.ts
Uncaught TypeError: TS2339 [ERROR]: Property 'toPrimitive' does not exist on type 'never'.
      const toPrimitiveSymbol = supportsSymbol && typeof Symbol.toPrimitive !== "undefined" ? Symbol.toPrimitive : "@@toPrimitive";
                                                                ~~~~~~~~~~~
    at https://deno.land/x/reflect_metadata@v0.1.12/Reflect.ts:664:65

TS2339 [ERROR]: Property 'toPrimitive' does not exist on type 'never'.
      const toPrimitiveSymbol = supportsSymbol && typeof Symbol.toPrimitive !== "undefined" ? Symbol.toPrimitive : "@@toPrimitive";
                                                                                                     ~~~~~~~~~~~
    at https://deno.land/x/reflect_metadata@v0.1.12/Reflect.ts:664:102

TS2339 [ERROR]: Property 'iterator' does not exist on type 'never'.
      const iteratorSymbol = supportsSymbol && typeof Symbol.iterator !== "undefined" ? Symbol.iterator : "@@iterator";
                                                             ~~~~~~~~
    at https://deno.land/x/reflect_metadata@v0.1.12/Reflect.ts:665:62

TS2339 [ERROR]: Property 'iterator' does not exist on type 'never'.
      const iteratorSymbol = supportsSymbol && typeof Symbol.iterator !== "undefined" ? Symbol.iterator : "@@iterator";
                                                                                               ~~~~~~~~
    at https://deno.land/x/reflect_metadata@v0.1.12/Reflect.ts:665:96

Found 4 errors.
    at async <anonymous>:2:22
```

**Comment by cmd-johnson** [comment]
Hi there!
This looks to be the same problem as #4. Try using the most recent version, which would be `https://deno.land/x/reflect_metadata@v0.1.12-2/mod.ts`.
